package sms.gui.admin;
import database.DatabaseConnection;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Admin_PaymentsView extends javax.swing.JFrame {
    
    private final int studentID;
    private double totalBill;  
    private double totalPaid;
   
    public Admin_PaymentsView(int ID) {
        initComponents();
        fetchPaymentData(ID);
        this.studentID = ID;
        getID.setText("Student ID: " + ID);
        calculateTotalBill(ID);
        updateAmountToPayLabel();
        calculateTotalPaid(ID);
        updateAmount_TotalPaid();
        updateAmount_Outstanding();
    }

    private Admin_PaymentsView() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    private void fetchPaymentData(int studentID) {
    String query = "SELECT paymentDate, amount FROM payment WHERE id = ?";
    try (Connection connection = DatabaseConnection.getConnection();
         PreparedStatement preparedStatement = connection.prepareStatement(query)) {
        preparedStatement.setInt(1, studentID);
        try (ResultSet resultSet = preparedStatement.executeQuery()) {
            
            String[] columnNames = {"Date", "Amount"};
            DefaultTableModel payment = new DefaultTableModel(columnNames, 0);
            while (resultSet.next()) {
                Date paymentDate = resultSet.getDate("paymentDate");
                double amount = resultSet.getDouble("amount");
                payment.addRow(new Object[]{paymentDate, amount});
            }
            paymentTable.setModel(payment);
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error");
    }
}
    private void calculateTotalBill(int studentID) {
    String query = "SELECT SUM(amount) AS total FROM bill WHERE id = ?";
    try (Connection connection = DatabaseConnection.getConnection();
         PreparedStatement preparedStatement = connection.prepareStatement(query)) {
        preparedStatement.setInt(1, studentID);
        try (ResultSet resultSet = preparedStatement.executeQuery()) {
            if (resultSet.next()) {
                this.totalBill = resultSet.getDouble("total"); 
            }
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error calculating total Bill");
    }
}

    private void calculateTotalPaid(int studentID)
    {
       String query = "SELECT SUM(amount) AS total FROM payment WHERE id = ?";
       try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement preparedStatement = connection.prepareStatement(query)) {
        preparedStatement.setInt(1, studentID);
        try (ResultSet resultSet = preparedStatement.executeQuery()) {
            if (resultSet.next()) {
                this.totalPaid = resultSet.getDouble("total");
            }
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error calculating total Payment");
    }

    }
    
    private void updateAmountToPayLabel() {
        amountTOPay.setText("" + totalBill);
    }
    private void updateAmount_TotalPaid()
     {
         totalPaidLable.setText(""+totalPaid);
     }
     
    private void updateAmount_Outstanding()
     {
        double outstandingAmount = totalBill - totalPaid;  
        outstanding.setText("" + outstandingAmount);
     }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        getID = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        paymentTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addPayment = new javax.swing.JButton();
        goDashboard = new javax.swing.JButton();
        amountTOPay = new javax.swing.JLabel();
        totalPaidLable = new javax.swing.JLabel();
        outstanding = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Payment ");
        setResizable(false);

        header.setBackground(new java.awt.Color(0, 122, 255));
        header.setPreferredSize(new java.awt.Dimension(800, 100));
        header.setLayout(new java.awt.GridBagLayout());

        getID.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        getID.setForeground(new java.awt.Color(255, 255, 255));
        getID.setText("Student Payment Information");
        header.add(getID, new java.awt.GridBagConstraints());

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(550, 500));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel3.setText("Payment Details");

        paymentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Date", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(paymentTable);
        if (paymentTable.getColumnModel().getColumnCount() > 0) {
            paymentTable.getColumnModel().getColumn(0).setResizable(false);
            paymentTable.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);

        jPanel3.setPreferredSize(new java.awt.Dimension(250, 500));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setText("Total Payable:");

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel4.setText("Total Outstanding:");

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel5.setText("Total Paid:");

        addPayment.setBackground(new java.awt.Color(0, 122, 255));
        addPayment.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addPayment.setForeground(new java.awt.Color(255, 255, 255));
        addPayment.setText("Add Payment");
        addPayment.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        addPayment.setBorderPainted(false);
        addPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPaymentActionPerformed(evt);
            }
        });

        goDashboard.setBackground(new java.awt.Color(0, 122, 255));
        goDashboard.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        goDashboard.setForeground(new java.awt.Color(255, 255, 255));
        goDashboard.setText("Back");
        goDashboard.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        goDashboard.setBorderPainted(false);
        goDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goDashboardActionPerformed(evt);
            }
        });

        amountTOPay.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        amountTOPay.setForeground(new java.awt.Color(255, 51, 0));
        amountTOPay.setText("amountTOPay");

        totalPaidLable.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        totalPaidLable.setText("Total Paid:");

        outstanding.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        outstanding.setText("DueAmount");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addPayment, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(goDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(amountTOPay)
                    .addComponent(totalPaidLable)
                    .addComponent(outstanding))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(amountTOPay)
                .addGap(7, 7, 7)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalPaidLable)
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outstanding)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(addPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(goDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jPanel1.add(jPanel3);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPaymentActionPerformed
    try {
        Admin_PaymentAdd newAddPayment = new Admin_PaymentAdd(studentID);
        newAddPayment.setVisible(true);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,"Error Adding new payment");
    }
    }//GEN-LAST:event_addPaymentActionPerformed

    private void goDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goDashboardActionPerformed

        this.dispose();
        Admin_Dashboard adminDashboard = new Admin_Dashboard();
        adminDashboard.setVisible(true);
    }//GEN-LAST:event_goDashboardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {  
            public void run() {
                new Admin_PaymentsView().setVisible(true);   
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPayment;
    private javax.swing.JLabel amountTOPay;
    private javax.swing.JLabel getID;
    private javax.swing.JButton goDashboard;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel outstanding;
    private javax.swing.JTable paymentTable;
    private javax.swing.JLabel totalPaidLable;
    // End of variables declaration//GEN-END:variables
}
